apiVersion: v1
kind: Secret
metadata:
  name: configuration-service-secrets
  namespace: grpc-playground
stringData:
  MONGODB_CONNECTION_STRING: {{ .Values.MONGODB_CONNECTION_STRING }}
  SERVICE_BUS_CONNECTION_STRING: {{ .Values.SERVICE_BUS_CONNECTION_STRING }}
type: Opaque
